<a href="https://colab.research.google.com/github/Muthon1/DataScience/blob/main/NumPy_Practice_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
# Create a 1D NumPy array with values from 0 to 9.
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)
# Create a 2D NumPy array with values from 1 to 9.
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2D)



[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Array Indexing and Slicing
# Access the 5th element of the 1D array created earlier.
index_fifth_number = array[5]
print(index_fifth_number)
# Access the element at row 2, column 3 of the 3x3 array
second_row = array_2D[1,:3]
print(second_row)
# Slice the 1D array to extract values from index 3 to 7
slice_array = array[3:8]
print(slice_array)
# Slice the 3x3 array to extract the second row
slice_array_2D = array_2D[1,:]
print(slice_array_2D)

5
[4 5 6]
[3 4 5 6 7]
[4 5 6]


In [17]:
# Array Operations
# Multiply all elements in the 1D array by 2
multiply_array = array * 2
print(multiply_array)
# Add 10 to all elements in the 3x3 array
add_array_2D = array_2D + 10
print(add_array_2D)
# Find the sum of all elements in the 1D array
sum_array = np.sum(array)
print(sum_array)
# Find the mean of all elements in the 3x3 array.
mean_array_2D = np.mean(array_2D)
print(mean_array_2D)


[ 0  2  4  6  8 10 12 14 16 18]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
45
5.0


In [21]:
# Mathematical Functions
# Generate a NumPy array of 10 evenly spaced values between 0 and 1
array_evenly_spaced = np.linspace(0,1,10)
print(array_evenly_spaced)
# Create a 1D array with 10 random integers between 1 and 50
array_random = np.random.randint(1,50,10)
print(array_random)
# Find the maximum and minimum values from the random array
max_array_random = np.max(array_random)
min_array_random = np.min(array_random)
print(max_array_random)
print(min_array_random)
# Calculate the standard deviation of the random array
standard_deviation = np.std(array_random)
print(standard_deviation)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[28 16  2 29 41 12 21  1  1  7]
41
1
13.059862173851606


In [23]:
# Reshaping Arrays
# Reshape the 1D array of random integers into a 2D array (2x5)
reshape_array = array_random.reshape(2,5)
print(reshape_array)
# Transpose the reshaped array
transpose_array = np.transpose(reshape_array)
print(transpose_array)

[[28 16  2 29 41]
 [12 21  1  1  7]]
[[28 12]
 [16 21]
 [ 2  1]
 [29  1]
 [41  7]]


In [25]:
# Logical Operations
# Create a boolean mask where elements in the 1D array of random integers are greater than 25.
boolean_mask = array_random > 25
print(boolean_mask)
# Use this mask to filter the elements in the array that are greater than 25
filter_array = array_random[boolean_mask]
print(filter_array)

[ True False False  True  True False False False False False]
[28 29 41]


In [28]:
# Bonus Challenge
# Create a 4x4 identity matrix using NumPy
import numpy as np
identity_matrix = np.identity(4)
print(identity_matrix)
# Create a diagonal matrix with values 1, 2, 3, 4 along its diagonal
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
